title: "Sandy Nandu"
tagline: "Data Science | AI | Machine Learning"
description: "Welcome to my portfolio. Showcasing my projects, skills, and achievements in Data Science."

author:
  name: "Sandy Nandu"
  location: "United States"
  university: "University of New Haven"
  email: "devakinandanpentyala2002@gmail.com"
  github: "Sandy-Nandu"
  linkedin: "www.linkedin.com/in/devakinandan-p"

theme: minimal-mistakes-jekyll
